//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestProj.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        public static string ActivateProjectStatusTermName {
            get {
                return ResourceManager.GetString("ActivateProjectStatusTermName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BelongToProject.
        /// </summary>
        public static string BelongToProjectFieldInternalName {
            get {
                return ResourceManager.GetString("BelongToProjectFieldInternalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belong to project.
        /// </summary>
        public static string BelongToProjectFieldTitleName {
            get {
                return ResourceManager.GetString("BelongToProjectFieldTitleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string CancelledProjectStatusTermName {
            get {
                return ResourceManager.GetString("CancelledProjectStatusTermName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract.
        /// </summary>
        public static string ContractDocumentTypeTermName {
            get {
                return ResourceManager.GetString("ContractDocumentTypeTermName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string DepartmentFieldInternalName {
            get {
                return ResourceManager.GetString("DepartmentFieldInternalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string DepartmentFieldTitleName {
            get {
                return ResourceManager.GetString("DepartmentFieldTitleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string DepartmentTermSetName {
            get {
                return ResourceManager.GetString("DepartmentTermSetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocumentResponsible.
        /// </summary>
        public static string DocumentResponsibleFieldInternalName {
            get {
                return ResourceManager.GetString("DocumentResponsibleFieldInternalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Responsible.
        /// </summary>
        public static string DocumentResponsibleFieldTitleName {
            get {
                return ResourceManager.GetString("DocumentResponsibleFieldTitleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocumentType.
        /// </summary>
        public static string DocumentTypeFieldInternalName {
            get {
                return ResourceManager.GetString("DocumentTypeFieldInternalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Type.
        /// </summary>
        public static string DocumentTypeFieldTitleName {
            get {
                return ResourceManager.GetString("DocumentTypeFieldTitleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string EndDateFieldInternalName {
            get {
                return ResourceManager.GetString("EndDateFieldInternalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string EndDateFieldTitle {
            get {
                return ResourceManager.GetString("EndDateFieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExpirationDate.
        /// </summary>
        public static string ExpirationDateFieldInternalName {
            get {
                return ResourceManager.GetString("ExpirationDateFieldInternalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration Date.
        /// </summary>
        public static string ExpirationDateFieldTitle {
            get {
                return ResourceManager.GetString("ExpirationDateFieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPMeta2.Samples.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HR.
        /// </summary>
        public static string HRDepartmentTermName {
            get {
                return ResourceManager.GetString("HRDepartmentTermName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managed Projects.
        /// </summary>
        public static string ManagedProjectsListViewTitleName {
            get {
                return ResourceManager.GetString("ManagedProjectsListViewTitleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MDIS.
        /// </summary>
        public static string MDISDepartmentTermName {
            get {
                return ResourceManager.GetString("MDISDepartmentTermName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-init phase.
        /// </summary>
        public static string PreInitPhaseProjectStatusTermName {
            get {
                return ResourceManager.GetString("PreInitPhaseProjectStatusTermName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string ProjectContemtTypeName {
            get {
                return ResourceManager.GetString("ProjectContemtTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Documents.
        /// </summary>
        public static string ProjectDocumentsListCustomUrlName {
            get {
                return ResourceManager.GetString("ProjectDocumentsListCustomUrlName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Documents.
        /// </summary>
        public static string ProjectDocumentsListTitleName {
            get {
                return ResourceManager.GetString("ProjectDocumentsListTitleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Document Type.
        /// </summary>
        public static string ProjectDocumentTypeTermSetName {
            get {
                return ResourceManager.GetString("ProjectDocumentTypeTermSetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProjectManager.
        /// </summary>
        public static string ProjectManagerFieldInternalName {
            get {
                return ResourceManager.GetString("ProjectManagerFieldInternalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Manager.
        /// </summary>
        public static string ProjectManagerFieldTitle {
            get {
                return ResourceManager.GetString("ProjectManagerFieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string ProjectsListCustomUrlName {
            get {
                return ResourceManager.GetString("ProjectsListCustomUrlName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string ProjectsListTitleName {
            get {
                return ResourceManager.GetString("ProjectsListTitleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Status.
        /// </summary>
        public static string ProjectStatusFieldTitle {
            get {
                return ResourceManager.GetString("ProjectStatusFieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProjectStatus.
        /// </summary>
        public static string ProjectStatusFieldTitleInternalName {
            get {
                return ResourceManager.GetString("ProjectStatusFieldTitleInternalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Status.
        /// </summary>
        public static string ProjectStatusTermSetName {
            get {
                return ResourceManager.GetString("ProjectStatusTermSetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProjectValue.
        /// </summary>
        public static string ProjectValueFieldInternalName {
            get {
                return ResourceManager.GetString("ProjectValueFieldInternalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project value.
        /// </summary>
        public static string ProjectValueFieldTitleName {
            get {
                return ResourceManager.GetString("ProjectValueFieldTitleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QA.
        /// </summary>
        public static string QADepartmentTermName {
            get {
                return ResourceManager.GetString("QADepartmentTermName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        public static string RejectedProjectStatusTermName {
            get {
                return ResourceManager.GetString("RejectedProjectStatusTermName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirements.
        /// </summary>
        public static string RequirementsDocumentTypeTermName {
            get {
                return ResourceManager.GetString("RequirementsDocumentTypeTermName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFX.
        /// </summary>
        public static string RFXDocumentTypeTermName {
            get {
                return ResourceManager.GetString("RFXDocumentTypeTermName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SD1.
        /// </summary>
        public static string SD1DepartmentTermName {
            get {
                return ResourceManager.GetString("SD1DepartmentTermName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SD2.
        /// </summary>
        public static string SD2DepartmentTermName {
            get {
                return ResourceManager.GetString("SD2DepartmentTermName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartDate.
        /// </summary>
        public static string StartDateFieldInternalName {
            get {
                return ResourceManager.GetString("StartDateFieldInternalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDateFieldTitle {
            get {
                return ResourceManager.GetString("StartDateFieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        public static string TeamFieldInternalName {
            get {
                return ResourceManager.GetString("TeamFieldInternalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        public static string TeamFieldTitleName {
            get {
                return ResourceManager.GetString("TeamFieldTitleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical version.
        /// </summary>
        public static string TechnicalVersionDocumentTypeTermName {
            get {
                return ResourceManager.GetString("TechnicalVersionDocumentTypeTermName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VladTest.
        /// </summary>
        public static string TestGroupName {
            get {
                return ResourceManager.GetString("TestGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WD.
        /// </summary>
        public static string WDDepartmentTermName {
            get {
                return ResourceManager.GetString("WDDepartmentTermName", resourceCulture);
            }
        }
    }
}
